# Generated by Django 6.0.2 on 2026-02-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('thumbnail', models.ImageField(upload_to='glasses/thumbnails/', verbose_name='Miniatura')),
                ('model_3d_file', models.FileField(upload_to='glasses/models/', verbose_name='Modelo 3D (.glb)')),
                ('scale_factor', models.FloatField(default=0.15, verbose_name='Factor de escala')),
                ('offset_x', models.FloatField(default=0.0, verbose_name='Desplazamiento X')),
                ('offset_y', models.FloatField(default=0.02, verbose_name='Desplazamiento Y')),
                ('offset_z', models.FloatField(default=0.0, verbose_name='Desplazamiento Z')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lente',
                'verbose_name_plural': 'Lentes',
                'ordering': ['-created_at'],
            },
        ),
    ]
